### ISSUE TITLE
Firefox watcher duplicate

### ISSUE THREAD

**Issue by mvujica** [HerringtonDarkholme/av-ts#14] opened 2016-11-14 20:21 UTC
I'm using av-ts in new part of my application and I'm experiencing some strange issues in my Firefox 49.0.2 for Windows. Everything works as expected in Chrome and IE. I can't replicate exact errors in this small test code but something is wrong with the watchers setup and they are always duplicated and double executed.
Attached Sample Code to reproduce, using av-ts, vue-router and webpack: [package.zip](https://github.com/HerringtonDarkholme/av-ts/files/590368/package.zip)

Console output Chrome:
![image](https://cloud.githubusercontent.com/assets/11364617/20280992/ff09a542-aaae-11e6-9a53-361a94457649.png)
![image](https://cloud.githubusercontent.com/assets/11364617/20281127/81d25f8c-aaaf-11e6-87fd-af6e9cef6b05.png)

Console output Firefox
![image](https://cloud.githubusercontent.com/assets/11364617/20281062/3e0fc7da-aaaf-11e6-9da2-78c3e8140013.png)
![image](https://cloud.githubusercontent.com/assets/11364617/20281086/5f71cb3a-aaaf-11e6-9277-a1ef1a84cf07.png)

IE11 is fine like Chrome.
I'm banging my head for last two days, have no clue, can you help please? Don't know if it's specific av-ts, vue or vue-router issue or some combination in my setup.

Thanks!

**Comment by HerringtonDarkholme** [comment] 2016-11-15 01:35
Thanks for trying avts out. But github issue is not a place for Q&A.

Please do provide a viable setup. I cannot even compile your provided example.

The rule of thumb is reduce to minimal. You can try removing av-ts, vue-router one by one. Also, printing out component's $options is helpful.

If you still need help, you can go to https://gitter.im/vuejs/vue or https://gitter.im/vuejs/vue

**Comment by HerringtonDarkholme** [comment] 2016-11-15 03:10
Confirmed. Firefox supports an obsolete `Object.prototype.watch` which breaks watch option merging.

You can add `Object.prototype.watch = undefined` to suppress this.

**Comment by mvujica** [comment] 2016-11-15 06:04
Code is as minimal as possible. Do you need any more info or data?

**Comment by HerringtonDarkholme** [comment] 2016-11-15 06:08
Hi, I have confirmed the problem is `Object.prorotype.watch` in Firefox.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

This is an unstandard option in firefox. I don't want to fix it.
You can workaround by two way

1. adding `Object.prototype.watch = undefined` to your main script, before any application code.
2. Adding `watch` option to every component like this. `@Component({watch: {}})`

**Comment by mvujica** [comment] 2016-11-15 06:17
Ok that's fair, please add info for developers, because Firefox is not some marginal browser. Again thanks for this library it is the only viable choice for Vue 2.0 and typescript currently.

**Comment by HerringtonDarkholme** [comment] 2016-11-15 06:30
OK, I will consider that. This only happens when you have a `Vue.mixin` call + watch options.

```ts
Vue.mixin({})
var someConfig = {}
var watchOpt = someConfig.watch || {} // this is problematic
watchOpt.prop = function() {}

Vue.extend(someConfig)
```

**Comment by HerringtonDarkholme** [comment] 2016-11-15 07:00
Fixed in 0.5.1.

**Closed by HerringtonDarkholme** 2016-11-15 07:00 UTC
Labels: bug, enhancement

**Comment by mvujica** [comment] 2016-11-15 07:36
Great thanks, will try later today and post results.

**Comment by mvujica** [comment] 2016-11-15 11:41
Excellent, tested my app in Firefox and no more watcher errors. 
These watchers have been killing me for days.
